### ISSUE TITLE
Play button

### ISSUE THREAD

**Issue by Aatmaj-Zephyr** [Aatmaj-Zephyr/Hangman#136]
Make play button of better shape than rectangle.

**Comment by Aatmaj-Zephyr** [comment]
Maybe oval shaped button may look better.

**Comment by KrystalJean** [comment]
I have been brainstorming for awhile on this, and had an idea to make the button an image of a pokeball.  I found an image of an open pokeball that does not block the text.  Do you like this idea, or have any suggestions about it?  Here are some screen shots showing each word  (Play, Next Round, Retry) fitting within the pokeball:

![pokeball-btn-play](https://user-images.githubusercontent.com/44277065/194229235-ad4f133a-a498-494b-a3cc-c12d4265b528.png)

![pokeball-btn-NextRound](https://user-images.githubusercontent.com/44277065/194229281-e2979fe4-503e-4924-ad92-87055888efc1.png)

![pokeball-btn-retry](https://user-images.githubusercontent.com/44277065/194229299-c7c111e3-eb3a-46da-8dad-927efd860a25.png)

Please let me know if you like it, and I will send over a pull request?

Thank you.

**Comment by Aatmaj-Zephyr** [comment]
Nice Work!
The only issue is that the words play and retry are not visible. You can fix this by using a closed Pokeball image over there.

**Comment by KrystalJean** [comment]
Thank you!  
So, the play and retry words, as well as, the next round, are all still using the color animation to keep flashing red, green, blue.  I think this helps them to be visible, but the screenshot just doesn't show well because that's the color it happened to be on for the shot.
Do you think the flashing colors will allow it to be visible enough? or should I still change that to a closed pokeball?

**Comment by Aatmaj-Zephyr** [comment]
closed pokeball will be bettter

**Comment by KrystalJean** [comment]
Ok, no problem.  I will get this fixed. Thank you.

**Comment by KrystalJean** [comment]
How about this one?

![screencapture-127-0-0-1-5500-2022-10-06-01_49_45](https://user-images.githubusercontent.com/44277065/194233717-2a724c6e-ebc5-45d2-a0af-96e3e4926e68.png)
![screencapture-127-0-0-1-5500-2022-10-06-01_49_30](https://user-images.githubusercontent.com/44277065/194233726-95eade01-620c-453c-ab91-e6c2854b991d.png)
![screencapture-127-0-0-1-5500-2022-10-06-01_48_51](https://user-images.githubusercontent.com/44277065/194233728-bd3413bf-5818-461b-b738-5d324081e44c.png)

**Comment by Aatmaj-Zephyr** [comment]
Nice

**Comment by KrystalJean** [comment]
Thank you! I will send the pull request.
