### ISSUE TITLE
Next round colors blinking too fast

### ISSUE THREAD

**Issue by Aatmaj-Zephyr** [Aatmaj-Zephyr/Hangman#137]
Next round colors are blinking too fast

**Comment by Aatmaj-Zephyr** [comment]
This issue is open for hacktoberfest

**Comment by jma26** [comment]
@Aatmaj-Zephyr Is this issue open for grabs? I'd love to work on this. I also wanted to confirm, is it this "Next round" colors you were talking about?
![Capture](https://user-images.githubusercontent.com/25625490/194483403-4a6d0f19-86c5-46e2-8e48-7e2885f4af2d.PNG)

**Comment by Aatmaj-Zephyr** [comment]
Yes.

**Comment by Aatmaj-Zephyr** [comment]
@jma26 are you still on this issue? 
In that case make sure your branch is up to date with main

**Comment by jma26** [comment]
@Aatmaj-Zephyr Yes! Sorry for the delay!
