### ISSUE TITLE
Redesigned intro page

### ISSUE THREAD

**Issue by wre9-tesh** [Aatmaj-Zephyr/Hangman#140]
I have made a redesigned intro page for this game. Would  like to add the template design to this project.

# ScreenShot

![Desktop - 1](https://user-images.githubusercontent.com/96977189/194389549-2591fd41-2520-4419-a66a-f6f34be2b3c6.png)

**Comment by Aatmaj-Zephyr** [comment]
Nice!
Please open a pull request. Make sure that it is aligned with the latest version and there are no conflicts.

**Comment by Aatmaj-Zephyr** [comment]
@wre9-tesh waiting for your pr.
Also please update your branch to match the recent pushes in case you are going to solve this issue to avoid any conflicts...

**Comment by wre9-tesh** [comment]
Working on it, will submit pr in a day or two

**Comment by wre9-tesh** [comment]
@Aatmaj-Zephyr my work was nearly completed but few recent prs have created many merge conflicts .It will take a little more time now.

**Comment by Aatmaj-Zephyr** [comment]
Sure take your time. I have fixed hangman.js
