### ISSUE TITLE
Make Text More Readable on Hangman Page

### ISSUE THREAD

**Issue by R-Lovelett** [Aatmaj-Zephyr/Hangman#141]
Hello! I saw your project, and enjoyed playing it a bit! Had no issues other than I think that the background of the page while guessing letters makes it hard to read the text that cycles on the bottom of the screen. I would like to remedy this, maybe by fading the background a bit or adding a faded color box where the text will be. Would you assign this to me?

**Comment by Aatmaj-Zephyr** [comment]
Sure
