### ISSUE TITLE
make pokeball clickable

### ISSUE THREAD

**Issue by Aatmaj-Zephyr** [Aatmaj-Zephyr/Hangman#143]
The play pokeball must grow in size when hovered on

**Comment by Aatmaj-Zephyr** [comment]
Code to fix

button#play:hover{
 height: 250px;
    width: 250px;
      transition: 1.5s;
}

**Comment by jma26** [comment]
@Aatmaj-Zephyr Is this issue open for grabs? I'd love to work on this enhancement. Thanks!

**Comment by Aatmaj-Zephyr** [comment]
Thanks @jma26 but i already have solved it using the above code. waiting for other prs so i can solve and merge mine.

**Comment by Aatmaj-Zephyr** [comment]
Fixed
