### ISSUE TITLE
Sudden transition of next button

### ISSUE THREAD

**Issue by Aatmaj-Zephyr** [Aatmaj-Zephyr/Hangman#145]
Next button is getting sudden appearance. Instead move it down gradually.

**Comment by ArinCodes** [comment]
Assign me this I'm a big pokemon fan

**Comment by ArinCodes** [comment]
Do You want me To just increase The Transition Time ? Or you want me to add an animation to it too..
(please describe the kind of animation if so?)

**Comment by Aatmaj-Zephyr** [comment]
Drop down animation

**Comment by Aatmaj-Zephyr** [comment]
Not working for game lost

**Comment by ArinCodes** [comment]
Done !!

**Comment by ArinCodes** [comment]
hey can you add hacktoberfest-acepted label in this too

**Comment by Aatmaj-Zephyr** [comment]
It is already added
