### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by Aatmaj-Zephyr** [Aatmaj-Zephyr/Hangman#206]
Add pokeball image to favicon

**Comment by wre9-tesh** [comment]
hey @Aatmaj-Zephyr  i was working on the the responsive design pr and i have two designs which one do u prefer?
Option - 1:
![image](https://user-images.githubusercontent.com/96977189/196709482-8c44f12a-d692-4303-b34a-7c78c5b66e3e.png)
Option - 2:
![image](https://user-images.githubusercontent.com/96977189/196710653-7791cd50-f3ed-4be9-ae8c-6d8b7ee278d7.png)

Or if you have any other designs do tell me .

BTW I have fixed this issue and will include it in this pr.
