### ISSUE TITLE
Website broken for desktop view

### ISSUE THREAD

**Issue by Aatmaj-Zephyr** [Aatmaj-Zephyr/Hangman#231]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/83284294/197318043-edf9e8b4-ea79-4b78-8ae4-ad25f767838d.png">

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/83284294/197318049-2e671108-fbaa-4c8b-8a2c-541c4ad7b224.png">

**Comment by Athi223** [comment]
I'd like to contribute to this, if it is available
